# Generated by Django 3.2 on 2021-05-05 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210505_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='card_num',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='card_type',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='card',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='card',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='card',
            name='ssn',
        ),
    ]
