# Generated by Django 3.2 on 2021-05-06 13:04

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.make_filename),
        ),
    ]
