# Generated by Django 3.2 on 2021-05-10 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_alter_address_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="card",
            options={"ordering": ["id"]},
        ),
    ]
