# Generated by Django 3.2 on 2021-05-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_additional_comments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
