# Generated by Django 3.2 on 2021-05-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('contents', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('weight', models.IntegerField(blank=True)),
                ('stock', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('total_score', models.FloatField(default=0)),
                ('total_reviews', models.IntegerField(default=0)),
                ('price', models.FloatField()),
                ('category', models.CharField(max_length=255)),
                ('percentage_off', models.FloatField(default=0)),
                ('picture', models.CharField(max_length=255)),
                ('labels', models.ManyToManyField(to='products.Label')),
            ],
        ),
    ]
