# Generated by Django 3.2 on 2021-05-10 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_label_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name']},
        ),
    ]
