# Generated by Django 3.2 on 2021-05-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_review_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='total_reviews',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total_score',
        ),
        migrations.AddField(
            model_name='product',
            name='review_calculated',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='total_review_score',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='total_reviewers',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
