# Generated by Django 3.2 on 2021-05-11 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_delete_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-id']},
        ),
    ]
