# Generated by Django 3.2 on 2021-05-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_review_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='products',
            field=models.ManyToManyField(through='products.ProductLabel', to='products.Product'),
        ),
    ]
