# Generated by Django 3.2 on 2021-05-13 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_label_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDiscount',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.product',),
        ),
        migrations.RemoveField(
            model_name='label',
            name='products',
        ),
    ]
