# Generated by Django 3.2 on 2021-05-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20210513_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
